language: go
go:
  - 1.15.x
env:
  global:
    - secure: ZkXULu7D0WlqpR9H/Uh4W4vZH38R3tA1lpTgfZTfiN+DdIJFljYI5mxjgYOttrfUTMdJJClRyx2zne1T7P6EhkUCEd/vjxNQszcho21YZ78JmbBOpVtKKWxseav0Yq1TJ3Y0YH2P7dv0HtgTnCC2CKsruy8fuZeK4jhx7m/YZ6lvtDmQ+L4IS59T6ZegcReqksRnV+mzQQVRswVzWekYnc6cB7xR3Sb+PmhdeJB8fWj4TOtwcF3xBw1kcPKmtkpKdDaVqnjLyMaQ60dQxyj114jJBAFJ19A7JM3+rI8WkhNygaMq5Q4KJsa0jNRICGDVAWkeLBOD2z7cUC+sXim7MuI36Wm+Ava0lY0AnjZttR1u2kKcuKUQ9NwaT+dvpH63naPj0OvEDuCVnrY8nxF6indF7urmzWrmz1RwfYVeFQIQsght/wue8ISGqLRX9qZnuopi9antAEGGNWhLLeUHZQMH/kG3JYv+QzRhxQygHyVaLzV6dcqh8+dmlPBjRh3II/HZBbERfxsa+z2oEPXXLC+ovUE4hHRjufzoxo8qAyz8tiU/3zpKViWpgciqe2T72NkAfs7mZ2hw1yGB3EJLla4jRQ/zzCEOWzXry7RrJJLdt4HGkMSthM8dwB1ufJOIEdmJuzAIeYxLfFWtSgXxjiEmsTHM4+i4IGf138LS2q8=
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script:
  - GOARCH=amd64 GOOS=linux go build -o "consul_members_exporter" ./...
  - go test -coverprofile c.out ${gobuild_args} ./...
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -p $(go list -m)"
deploy:
  provider: releases
  api_key:
    secure: OPxunInPnrK7QiahzXKxlTpPYJZ4GQXi3GJ0Z/xrGx3Wlnv0O176TMfsQWoluAW8JgTpQhAOsVwIMoPXa8rjJR6kvZK9n+N00H0ThpsBbKnWYuVlb3bguDdDIvsA2zndoKSv+3VaCeoEwhSgsY7h40qQwSx0VxZtPyx3XkmpNrxPsjxbDzBx5K1Fo43GTNM3wMDYCEXAJYLf9wbnrZXNKWSoZaxnAraDu4mMo1gAaJmqB40IkcgLWhStZYZOHsEQJJVA1MKquLvOnyNrai2T0nzPXza2LdjihNw5F8mA+jNTFHZ4usp508RaAZaeyXfHKkiuKFRDG4K4FWqTtjiBWBnKmzonvay895Neiv8eAJ8OQAePqWq6/Mn76yoBRk42qKO0H0IX8fD5q4mMjnLhra3MW9im+S4oVkKWcT3pl7f1OvBFhwyVUmbjpbPZBFGl+QOBu1KPQ4ocechxc6MW/LN0Xbt81AfQWoh1weOyKONu40KUwJMqcVXMAiJHzJt8tAZ62w/okG4j/tXXGtguZ7F75Kh7hbeDMkGdahAWUdhg/bOJT7eOUVdnfTN3Zb0F/Uw5CkQYKVT8WXRYRC4JZh+8fxnBYf3QvvDC3fkZVrA9VzxSEEOyg6uLZZucOR6gywyNaWcjwd2fJXtDHbQrciMIBLcB3WBt9oXzvyGzMtY=
  file: consul_members_exporter
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
