language: go
go:
  - 1.15.x
env:
  global:
    - secure: ZkXULu7D0WlqpR9H/Uh4W4vZH38R3tA1lpTgfZTfiN+DdIJFljYI5mxjgYOttrfUTMdJJClRyx2zne1T7P6EhkUCEd/vjxNQszcho21YZ78JmbBOpVtKKWxseav0Yq1TJ3Y0YH2P7dv0HtgTnCC2CKsruy8fuZeK4jhx7m/YZ6lvtDmQ+L4IS59T6ZegcReqksRnV+mzQQVRswVzWekYnc6cB7xR3Sb+PmhdeJB8fWj4TOtwcF3xBw1kcPKmtkpKdDaVqnjLyMaQ60dQxyj114jJBAFJ19A7JM3+rI8WkhNygaMq5Q4KJsa0jNRICGDVAWkeLBOD2z7cUC+sXim7MuI36Wm+Ava0lY0AnjZttR1u2kKcuKUQ9NwaT+dvpH63naPj0OvEDuCVnrY8nxF6indF7urmzWrmz1RwfYVeFQIQsght/wue8ISGqLRX9qZnuopi9antAEGGNWhLLeUHZQMH/kG3JYv+QzRhxQygHyVaLzV6dcqh8+dmlPBjRh3II/HZBbERfxsa+z2oEPXXLC+ovUE4hHRjufzoxo8qAyz8tiU/3zpKViWpgciqe2T72NkAfs7mZ2hw1yGB3EJLla4jRQ/zzCEOWzXry7RrJJLdt4HGkMSthM8dwB1ufJOIEdmJuzAIeYxLfFWtSgXxjiEmsTHM4+i4IGf138LS2q8=
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
script:
  - GOARCH=amd64 GOOS=linux go build -o "consul_members_exporter" ./...
  - go test -coverprofile c.out ${gobuild_args} ./...
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -p $(go list -m)"
deploy:
  provider: releases
  api_key:
    secure: O8ApDHAerAQ67KpHQvfF5iiwCprnXVb8BOPJoves8XN+PahDbEvHVx7s7IuY2KCNDwnsTjoGeKwih5UFmD6zzf81iLHEUC7TmQa9U1xfkJtj8fLWOM+g3fWe2czE/XnsElTkPC2/SDFga/95LzsFMr0Hy6j9oBAAkwb6U7y1w+e7fhZ861Lij2j7og3GDNNJwDchotXtvr/A86Pg8m1c6w3zAqhEf+YCvNsBs7y02yFK96WckoBlp+LDnOquBPi8Ypn5cUxaY4i9TPAgYbzTN037nrLfHU+3IxoX6vOnsRcZoA2yeg84/YzjoqvDgYbemuschLxfghoziOOnWTknYLGZUvsp3JCEG2msuHXT6d60TwDOKsrsu/OtEmMvGbG3Ab75OqxEGpcdRRY//qVQnPYT/wQSiFQYxDit7DZXX5anh3HktD+KFh1LlJZyUxN+yNFWQ0pyXMVyQDFtM6ghHJQknSwbZyB8au8CiVh7zVQBo1yVxjqoFhP9hJIbGsHA3sjAY/vvhELh6ldwlawqcK2LdrDqy4tvXmt2jRoaOpprd9UPeq0daaHq//XgUvtrJmGeDN/uVF5wsmp5AP5zz12inPOUtci9RTWaOn4oPc76vNgrbVzK7Jw+aFhlYzwVYElJZ/ZTJBV++1G5QCgL1BvHnKGfkl+kCael10QhkLo=
  file: consul_members_exporter
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
